project:
  resources: 
    - media/resume_temp.pdf # will need to be changed later
  type: website
  output-dir: docs

website:
  title: "Henry Strecker"
  navbar:
    left:
      - href: index.qmd
        icon: house-fill
        text: "Home"
      - text: "Projects"
        menu: 
          - text: "Research: Biomass and Land Use in a Decarbonizing US"
            href: biomass.qmd
          - text: "Masters Thesis: Solstice Health"
            href: solstice_health.qmd
          - text: "Guest Lecture: Environmental Data Science"
            href: lecture.qmd
          - text: "Dashboard: Low-Carbon Electricity for Southern Africa"
            href: africa_electric.qmd
          - text: "Dashboard: Nitrates in California Groundwater Wells"
            href: nitrate.qmd
          - text: "Energy Demand Analysis: Freight Transport"
            href: freight.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full



