project:
  type: website
  output-dir: docs

website:
  title: "Henry Strecker"
  navbar:
    left:
      - href: index.qmd
        icon: house-fill
        text: Home
      - about.qmd
      - lecture.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full



