---
title: "Energy Demand Analysis - Freight Tansport"
editor: source
toc: false
---

This report comes from one of my favorite projects I have completed in any course to date. In this course called *Energy Demand Analysis*, groups were split up to research and develop a "Low Energy and Emissions Scenario" for a sector that has historically high energy consumption. My team was tasked with looking at freight transportation in the United States spanning trucking, aviation, rail, and inland water fleets. We began by calculating a future projection of energy demand for 2050 based on historical trends in the sector. That projection became the motivation for deploying all of our interventions, policy suggestions, and technology adoption. I spent most of my efforts modeling electrified short haul aviation (less than 200 miles), as well as shifting water fleets and tugboats to utilize ammonia as fuel. My colleagues devised strategies to increase rail capacity, as that is the most efficient transportation method, as well as reducing trucking miles and emissions through electrification.


---

<iframe src="media/freight_report.pdf" width="100%" height="1100px" style="border: 2px solid #ddd; box-shadow: 5px 5px 15px rgba(0,0,0,0.2); border-radius: 10px;"> </iframe>
---